#!/usr/bin/env python3
#
# Fetch the releases.json file from the remote endpoint and format it.
# Copyright Linux Foundation
# Author: Antonin Godard <antonin.godard@bootlin.com>
#
# SPDX-License-Identifier: MIT
#

import argparse
import json

from pathlib import Path
from urllib.request import urlopen


def main():

    parser = argparse.ArgumentParser(description="Fetch and format releases.json")
    parser.add_argument("output", type=Path, help="Output releases.json file")
    args = parser.parse_args()

    with urlopen("https://dashboard.yoctoproject.org/releases.json") as req:
        releases = json.load(req)
        with open(args.output, "w") as f:
            json.dump(releases, f, indent=2)


if __name__ == "__main__":
    main()
